compile:
	g++ main.cpp -lgdi32 -o main -O3
compileO:
	g++ main.cpp -lgdi32 -o main
run:
	./main.exe

xcompile:
	g++ main.cpp -o xmain -O3
xcompileO:
	g++ main.cpp -o xmain
xrun:
	./xmain.exe

mazetest:
	g++ mazetest.cpp -o mazetest
	./mazetest.exe