compile:
	g++ main.cpp -lgdi32 -o main -O3
compileO:
	g++ main.cpp -lgdi32 -o main
run:
	./main
runexe:
	./main.exe

xcompile:
	g++ xmain.cpp -o xmain.o -lX11 -O3
xcompileO:
	g++ xmain.cpp -o xmain.o -lX11
xrun:
	./xmain.o

mazetest:
	g++ mazetest.cpp -o mazetest
	./mazetest.exe